---
- name: Shadowsocks with v2ray setup
  hosts: all
  remote_user: root
  roles:
    - common
    - shadowsocks_tuning
    - role: docker
      vars:
        docker_compose_version: "1.27.4"
    - proxy

  vars_files:
    - vars.yml

  vars_prompt:
    - name: shadowsocks_password
      prompt: "Shadowsocks password"
      private: yes
      confirm: yes